Traceback (most recent call last):
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We import all the necesary packages
import time
import os
from dotenv import load_dotenv
load_dotenv()
_PROJECT_PATH: str = os.environ["_project_path"]
_PICKLED_DATA_FILENAME: str = os.environ["_pickled_data_filename"]

import sys
from pathlib import Path
project_path = Path(_PROJECT_PATH)
sys.path.append(str(project_path))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdotenv[39;00m [38;5;28;01mimport[39;00m load_dotenv
[0;32m      5[0m load_dotenv()
[1;32m----> 6[0m _PROJECT_PATH: [38;5;28mstr[39m [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43m_project_path[39;49m[38;5;124;43m"[39;49m[43m][49m
[0;32m      7[0m _PICKLED_DATA_FILENAME: [38;5;28mstr[39m [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124m_pickled_data_filename[39m[38;5;124m"[39m]
[0;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m

File [1;32m~\.conda\envs\nuevo2-env\lib\os.py:679[0m, in [0;36m_Environ.__getitem__[1;34m(self, key)[0m
[0;32m    676[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;28mself[39m[38;5;241m.[39mencodekey(key)]
[0;32m    677[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[0;32m    678[0m     [38;5;66;03m# raise KeyError with the original key value[39;00m
[1;32m--> 679[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;28mNone[39m
[0;32m    680[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mdecodevalue(value)

[1;31mKeyError[0m: '_project_path'
KeyError: '_project_path'

